
name: .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:



    runs-on: windows-latest 
    env:
      Solution_Name: WindowFormDevOps/WindowFormDevOps.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: WindowFormDevOps/WindowFormDevOps/WindowFormDevOps.csproj            
      Wap_Project_Directory: WindowFormDevOps/WindowFormDevOps/
      Wap_Project_Path: WindowFormDevOps/WindowFormDevOps/Artifacts/                  

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    
    - name: Create Build Directory
      run: mkdir _build
  
    - name: Restore Packages
      run: nuget restore $env:Solution_Name
      
    - name: Build the application
      run: |
            msbuild.exe $env:Solution_Name /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
            
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WindowFormDevOpsBundle
        path: "./_build" 
     


